// <auto-generated />
namespace Projekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class zamina_modelu_produktu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zamina_modelu_produktu));
        
        string IMigrationMetadata.Id
        {
            get { return "201805141848277_zamina_modelu_produktu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
