// <auto-generated />
namespace Projekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class utworzenie_baz_produkt_uzytkownik : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(utworzenie_baz_produkt_uzytkownik));
        
        string IMigrationMetadata.Id
        {
            get { return "201805092236144_utworzenie_baz_produkt_uzytkownik"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
